import { Part } from './types';

export enum ComponentID {
  VACUUM_PUMP = 'vacuum_pump',
  SCRUBBER = 'scrubber',
  COMPRESSOR = 'compressor',
  MOTOR = 'motor',
  COOLING_UNIT = 'cooling_unit',
  CONTROL_SYSTEM = 'control_system',
  OIL_PUMP = 'oil_pump',
}

export const PARTS: Part[] = [
  {
    id: ComponentID.VACUUM_PUMP,
    name: 'Vacuum Pump',
    position: [0, 0.5, -1.5],
    focusPoint: [0, 0.5, -1.5],
    description: 'A pump that removes gas molecules from a sealed volume to leave behind a partial vacuum.',
    info: 'Efficiently removes gases to maintain optimal system pressure.',
    specs: { 'Power': '5 kW', 'Flow Rate': '100 m³/h' },
    pdfLink: '/pdfs/vacuum_pump_spec.pdf',
  },
  {
    id: ComponentID.SCRUBBER,
    name: 'Scrubber',
    position: [-1.5, 1.25, 0],
    focusPoint: [-1.5, 1.25, 0],
    description: 'A device that controls gaseous emissions, especially acid gases.',
    info: 'Removes pollutants from exhaust gases.',
    specs: { 'Capacity': '5000 CFM', 'Efficiency': '99%' },
    pdfLink: '/pdfs/scrubber_spec.pdf',
  },
  {
    id: ComponentID.COMPRESSOR,
    name: 'Compressor',
    position: [1.5, 0.5, 0],
    focusPoint: [1.5, 0.5, 0],
    description: 'A mechanical device that increases the pressure of a gas by reducing its volume.',
    info: 'Compresses gases for various industrial applications.',
    specs: { 'Pressure': '10 bar', 'Motor Power': '7.5 kW' },
    pdfLink: '/pdfs/compressor_spec.pdf',
  },
  {
    id: ComponentID.MOTOR,
    name: 'Motor',
    position: [1.5, 0.5, -1.5],
    focusPoint: [1.5, 0.5, -1.5],
    description: 'An electric motor that converts electrical energy into mechanical energy.',
    info: 'Powers the vacuum pump and compressor.',
    specs: { 'Type': 'AC Induction', 'RPM': '1500' },
    pdfLink: '/pdfs/motor_spec.pdf',
  },
  {
    id: ComponentID.COOLING_UNIT,
    name: 'Cooling Unit',
    position: [1.5, 1.5, 0],
    focusPoint: [1.5, 1.5, 0],
    description: 'A system that removes heat from a process or space.',
    info: 'Maintains optimal operating temperatures for sensitive components.',
    specs: { 'Cooling Capacity': '20 kW', 'Refrigerant': 'R-410A' },
    pdfLink: '/pdfs/cooling_unit_spec.pdf',
  },
  {
    id: ComponentID.CONTROL_SYSTEM,
    name: 'PLC Control System',
    position: [0, 0.5, 1.5],
    focusPoint: [0, 0.5, 1.5],
    description: 'A Programmable Logic Controller (PLC) based control system for automated operation.',
    info: 'Manages and monitors all VRU operations.',
    specs: { 'Processor': 'Dual Core', 'Memory': '4 GB' },
    pdfLink: '/pdfs/control_system_spec.pdf',
  },
  {
    id: ComponentID.OIL_PUMP,
    name: 'Oil Pump',
    position: [0, -0.5, 1.5],
    focusPoint: [0, -0.5, 1.5],
    description: 'A pump designed to circulate oil, typically for lubrication or hydraulic systems.',
    info: 'Ensures proper lubrication and fluid transfer within the system.',
    specs: { 'Flow Rate': '10 L/min', 'Pressure': '5 bar' },
    pdfLink: '/pdfs/oil_pump_spec.pdf',
  },
];